### ISSUE TITLE
salt shaker fails with: Formula marked as resolved but target XYZ didn't exist

### ISSUE THREAD

**Issue by munhitsu** [ministryofjustice/cotton#48]
having formula-requirements.txt:
git@github.com:ministryofjustice/admins-formula.git==v1.1.0
git@github.com:ministryofjustice/bootstrap-formula.git==v2.1.0
git@github.com:ministryofjustice/firewall-formula.git==v1.2.0-rc.pvb.1
git@github.com:ministryofjustice/salt-formula.git==v1.0.0
git@github.com:ministryofjustice/hosts-formula.git==v2.0.0
git@github.com:ministryofjustice/hardening-formula.git==v1.2.2
git@github.com:ministryofjustice/ntp-formula.git==v1.0.1
git@github.com:ministryofjustice/bootstrap-formula.git==v2.0.0
git@github.com:ministryofjustice/repos-formula.git==v1.1.1
git@github.com:ministryofjustice/jenkins-formula.git==v1.0.5
git@github.com:ministryofjustice/nginx-formula.git==v3.2.0
git@github.com:ministryofjustice/monitoring-formula.git==v1.0.3
git@github.com:ministryofjustice/sensu-formula.git==v4.4.2
git@github.com:ministryofjustice/utils-formula.git==v1.0.1
git@github.com:ministryofjustice/elasticsearch-formula.git==v1.3.1
git@github.com:ministryofjustice/redis-formula.git==v1.0.1

we get ourput:
(opg-zero)mateusz4moj-4:opg-basement-deply mlmalawski$ fab shaker
Fetching git@github.com:ministryofjustice/admins-formula.git done
Fetching git@github.com:ministryofjustice/bootstrap-formula.git done
Fetching git@github.com:ministryofjustice/firewall-formula.git done
Fetching git@github.com:ministryofjustice/salt-formula.git done
Fetching git@github.com:ministryofjustice/hosts-formula.git done
Fetching git@github.com:ministryofjustice/hardening-formula.git done
Fetching git@github.com:ministryofjustice/ntp-formula.git done
Fetching git@github.com:ministryofjustice/repos-formula.git done
Fetching git@github.com:ministryofjustice/jenkins-formula.git done
Fetching git@github.com:ministryofjustice/nginx-formula.git done
Fetching git@github.com:ministryofjustice/monitoring-formula.git done
Fetching git@github.com:ministryofjustice/sensu-formula.git done
Fetching git@github.com:ministryofjustice/utils-formula.git done
Fetching git@github.com:ministryofjustice/elasticsearch-formula.git done
Fetching git@github.com:ministryofjustice/redis-formula.git done
Fetching git@github.com:ministryofjustice/logstash-formula.git done
Fetching git@github.com:ministryofjustice/java-formula.git done
Fetching git@github.com:ministryofjustice/python-formula.git done
Fetching git@github.com:ministryofjustice/supervisor-formula.git done
Fetching git@github.com:ministryofjustice/apparmor-formula.git done
Traceback (most recent call last):
  File "/Users/mlmalawski/.virtualenvs/opg-zero/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Users/mlmalawski/.virtualenvs/opg-zero/lib/python2.7/site-packages/fabric/tasks.py", line 424, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/mlmalawski/.virtualenvs/opg-zero/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/mlmalawski/repos/cotton/cotton/salt_shaker.py", line 501, in shaker
    shaker_instance.install_requirements()
  File "/Users/mlmalawski/repos/cotton/cotton/salt_shaker.py", line 252, in install_requirements
    (repo_dir, _) = self.install_requirement(formula)
  File "/Users/mlmalawski/repos/cotton/cotton/salt_shaker.py", line 302, in install_requirement
    raise RuntimeError("%s: Formula marked as resolved but target '%s' didn't exist" % (formula['name'], target))
RuntimeError: python: Formula marked as resolved but target '/Users/mlmalawski/repos/opg-basement-deply/vendor/_root/python' didn't exist

**Comment by ashb** [comment]
That error sucks - we will fix that.

The actual error here is that python v1.0.0 is broken and tagged in the wrong place - v1.0.0 has no python/ directory in the repo.
